### ISSUE TITLE
Incorrect volume from H-rep

### ISSUE THREAD

**Issue by ferrolho** [JuliaPolyhedra/QHull.jl#29]
Still concerning the notebook of the previous issue:
![Screenshot from 2019-07-12 15-14-54](https://user-images.githubusercontent.com/4166093/61134639-f0f3f100-a4b7-11e9-9210-392035c61365.png)
_Originally posted by @ferrolho in https://github.com/JuliaPolyhedra/QHull.jl/issues/27#issuecomment-510903276_

The value computed and stored for `p3` is incorrect:
```julia
julia> @show volume(p1) volume(p2) volume(p3);
volume(p1) = 1.0
volume(p2) = 1.0
volume(p3) = 85.33333333333336
```

This is still related to the _H_-rep, as demonstrated by the following snippets:
```julia
julia> volume(polyhedron(hrep(p3), lib))
85.33333333333336
```
Constructing a new polyhedron from the _V_-rep yields the correct volume of the convex set:
```julia
julia> volume(polyhedron(vrep(p3), lib))
0.125
```

**Comment by blegat** [comment]
Indeed, the volume computed in `qhull(::MixedMatHRep)` is the volume of the polar of the shifted polytope so we cannot use it for the polar of the polytope.

**Comment by ferrolho** [comment]
This time I do not understand the fix; I lack the knowledge of what is going on at the algorithmic level... Anyway, thanks once again! :smiley:

**Comment by blegat** [comment]
QHull only supports the transformation from V-rep to H-rep so when I need to do the opposite, the H-rep is shifted so that the origin is in the interior and then the H-rep is transformed to the V-rep of the polar set so using QHull we get the H-rep of the polar set which is then turned into the V-rep of the shifted set and then it's shifted back :)
